In [11]:
import numpy as np
import pandas as pd

data_dir = '~/instacart_data/'
orders = pd.read_csv(data_dir + 'orders.csv', dtype={
        'order_id': np.int32,
        'user_id': np.int32,
        'eval_set': 'category',
        'order_number': np.int16,
        'order_dow': np.int8,
        'order_hour_of_day': np.int8,
        'days_since_prior_order': np.float32})
orders_prior = pd.read_csv(data_dir + 'order_products__prior.csv', dtype={
            'order_id': np.int32,
            'product_id': np.uint16,
            'add_to_cart_order': np.int16,
            'reordered': np.int8})
orders_train = pd.read_csv(data_dir + 'order_products__train.csv', dtype={
            'order_id': np.int32,
            'product_id': np.uint16,
            'add_to_cart_order': np.int16,
            'reordered': np.int8})

df = pd.concat((orders_train, orders_prior), axis=0)
#df = orders.merge(df, on='order_id', how='left')

#df.to_csv(data_dir + 'orders_full.csv', index=False)

In [12]:
orders_prior.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [13]:
orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [4]:
df_merged = orders.merge(df, on='order_id', how='left')

0            1.0
1            2.0
2            3.0
3            4.0
4            5.0
5            1.0
6            2.0
7            3.0
8            4.0
9            5.0
10           6.0
11           1.0
12           2.0
13           3.0
14           4.0
15           5.0
16           1.0
17           2.0
18           3.0
19           4.0
20           5.0
21           1.0
22           2.0
23           3.0
24           4.0
25           5.0
26           6.0
27           7.0
28           8.0
29           1.0
            ...
33894076     8.0
33894077     9.0
33894078    10.0
33894079    11.0
33894080    12.0
33894081    13.0
33894082    14.0
33894083    15.0
33894084    16.0
33894085    17.0
33894086    18.0
33894087    19.0
33894088    20.0
33894089     1.0
33894090     2.0
33894091     3.0
33894092     4.0
33894093     5.0
33894094     6.0
33894095     7.0
33894096     8.0
33894097     9.0
33894098     1.0
33894099     2.0
33894100     3.0
33894101     4.0
33894102     5.0
33894103     6.0
33894104     7.0
33894105     8.0
Name: add_to_cart_order, Length: 33894106, dtype: float64

In [ ]:
df_merged.join

In [15]:
df_merged['add_to_cart_order']

0            1.0
1            2.0
2            3.0
3            4.0
4            5.0
5            1.0
6            2.0
7            3.0
8            4.0
9            5.0
10           6.0
11           1.0
12           2.0
13           3.0
14           4.0
15           5.0
16           1.0
17           2.0
18           3.0
19           4.0
20           5.0
21           1.0
22           2.0
23           3.0
24           4.0
25           5.0
26           6.0
27           7.0
28           8.0
29           1.0
            ...
33894076     8.0
33894077     9.0
33894078    10.0
33894079    11.0
33894080    12.0
33894081    13.0
33894082    14.0
33894083    15.0
33894084    16.0
33894085    17.0
33894086    18.0
33894087    19.0
33894088    20.0
33894089     1.0
33894090     2.0
33894091     3.0
33894092     4.0
33894093     5.0
33894094     6.0
33894095     7.0
33894096     8.0
33894097     9.0
33894098     1.0
33894099     2.0
33894100     3.0
33894101     4.0
33894102     5.0
33894103     6.0
33894104     7.0
33894105     8.0
Name: add_to_cart_order, Length: 33894106, dtype: float64

In [ ]:
df_merged.dropna()

In [20]:
import numpy as np
import pandas as pd
#import lightgbm as lgb
IDIR = '~/instacart_data/'
data_dir = '~/instacart_data/'

print('loading prior')
priors = pd.read_csv(IDIR + 'order_products__prior.csv', dtype={
            'order_id': np.int32,
            'product_id': np.uint16,
            'add_to_cart_order': np.int16,
            'reordered': np.int8})

print('loading train')
train = pd.read_csv(IDIR + 'order_products__train.csv', dtype={
            'order_id': np.int32,
            'product_id': np.uint16,
            'add_to_cart_order': np.int16,
            'reordered': np.int8})

print('loading orders')
orders = pd.read_csv(IDIR + 'orders.csv', dtype={
        'order_id': np.int32,
        'user_id': np.int32,
        'eval_set': 'category',
        'order_number': np.int16,
        'order_dow': np.int8,
        'order_hour_of_day': np.int8,
        'days_since_prior_order': np.float32})

print('loading products')
products = pd.read_csv(IDIR + 'products.csv', dtype={
        'product_id': np.uint16,
        'order_id': np.int32,
        'aisle_id': np.uint8,
        'department_id': np.uint8},
        usecols=['product_id', 'aisle_id', 'department_id'])

print('priors {}: {}'.format(priors.shape, ', '.join(priors.columns)))
print('orders {}: {}'.format(orders.shape, ', '.join(orders.columns)))
print('train {}: {}'.format(train.shape, ', '.join(train.columns)))

###

print('computing product f')
prods = pd.DataFrame()
prods['orders'] = priors.groupby(priors.product_id).size().astype(np.int32)
prods['reorders'] = priors['reordered'].groupby(priors.product_id).sum().astype(np.float32)
prods['reorder_rate'] = (prods.reorders / prods.orders).astype(np.float32)
products = products.join(prods, on='product_id')
products.set_index('product_id', drop=False, inplace=True)
del prods


print('add order info to priors')
orders.set_index('order_id', inplace=True, drop=False)
items = priors.join(orders, on='order_id', rsuffix='_')
items.drop('order_id_', inplace=True, axis=1)

loading prior
loading train
loading orders
loading products
priors (32434489, 4): order_id, product_id, add_to_cart_order, reordered
orders (3421083, 7): order_id, user_id, eval_set, order_number, order_dow, order_hour_of_day, days_since_prior_order
train (1384617, 4): order_id, product_id, add_to_cart_order, reordered
computing product f
add order info to priors

In [23]:
products

,product_id,aisle_id,department_id,orders,reorders,reorder_rate
product_id,,,,,,
1,1,61,19,1852.0,1136.0,0.613391
2,2,104,13,90.0,12.0,0.133333
3,3,94,7,277.0,203.0,0.732852
4,4,38,1,329.0,147.0,0.446809
5,5,5,13,15.0,9.0,0.600000
6,6,11,11,8.0,3.0,0.375000
7,7,98,7,30.0,12.0,0.400000
8,8,116,1,165.0,83.0,0.503030
9,9,120,16,156.0,82.0,0.525641
10,10,115,7,2572.0,1304.0,0.506998
11,11,31,7,104.0,59.0,0.567308
12,12,119,1,246.0,126.0,0.512195
13,13,11,11,9.0,3.0,0.333333
14,14,74,17,17.0,2.0,0.117647
15,15,56,18,4.0,1.0,0.250000
16,16,103,19,19.0,2.0,0.105263
17,17,35,12,18.0,2.0,0.111111
18,18,79,1,137.0,82.0,0.598540
19,19,63,9,4.0,0.0,0.000000
20,20,98,7,6.0,1.0,0.166667
21,21,40,8,10.0,2.0,0.200000
22,22,20,11,43.0,19.0,0.441860
23,23,49,12,1068.0,479.0,0.448502
24,24,47,11,13.0,6.0,0.461538
25,25,3,19,2166.0,1391.0,0.642198
26,26,41,8,334.0,247.0,0.739521
27,27,127,11,184.0,77.0,0.418478
28,28,121,14,706.0,369.0,0.522663
29,29,81,15,218.0,81.0,0.371560
30,30,38,1,81.0,37.0,0.456790
...,...,...,...,...,...,...
49659,49659,17,13,256.0,55.0,0.214844
49660,49660,22,11,6.0,0.0,0.000000
49661,49661,134,5,13.0,9.0,0.692308
49662,49662,107,19,26.0,11.0,0.423077
49663,49663,57,14,12.0,3.0,0.250000
49664,49664,100,21,188.0,90.0,0.478723
49665,49665,45,19,106.0,53.0,0.500000
49666,49666,61,19,5.0,0.0,0.000000
49667,49667,38,1,1611.0,878.0,0.545003
49668,49668,101,17,378.0,192.0,0.507937
49669,49669,100,21,7.0,2.0,0.285714
49670,49670,106,12,229.0,112.0,0.489083
49671,49671,45,19,65.0,39.0,0.600000
49672,49672,26,7,14.0,4.0,0.285714
49673,49673,129,1,26.0,11.0,0.423077
49674,49674,37,1,88.0,60.0,0.681818
49675,49675,26,7,75.0,38.0,0.506667
49676,49676,64,7,50.0,22.0,0.440000
49677,49677,59,15,221.0,72.0,0.325792
49678,49678,129,1,377.0,149.0,0.395225
49679,49679,61,19,132.0,40.0,0.303030
49680,49680,89,13,1018.0,300.0,0.294695
49681,49681,38,1,70.0,39.0,0.557143
49682,49682,98,7,108.0,38.0,0.351852
49683,49683,83,4,97315.0,67313.0,0.691702
49684,49684,124,5,9.0,1.0,0.111111
49685,49685,42,1,49.0,6.0,0.122449
49686,49686,112,3,120.0,84.0,0.700000
49687,49687,41,8,13.0,6.0,0.461538
49688,49688,73,11,89.0,15.0,0.168539